// Exercise demo links + coaching cues transcribed from Fin Grathwol's
// original program PDF (each exercise name was hyperlinked to a YouTube
// form demo). Single source of truth shared by seed-workout-exercises.js
// (fresh installs) and add-exercise-videos.js (backfill onto existing rows).
// Keys are the exact exercise `name`s in the library.
export const EXERCISE_VIDEOS = {
  "1/2 Kneeling Cable Rotation": "https://www.youtube.com/shorts/JU_P4iLU-dM",
  "1/2 Kneeling Cable Row": "https://www.youtube.com/shorts/IJNHCNaY1vE",
  "1/2 Kneeling Landmine Press": "https://www.youtube.com/watch?v=fx6lSVNvu-4",
  "10 Kneeling Windmill Press": "https://www.youtube.com/shorts/UzCbtDBQ8t4",
  "BB RDL": "https://www.youtube.com/shorts/g5u75sgpn04",
  "Bear Crawl Openers": "https://www.youtube.com/shorts/Jk2MppyXyO8",
  "Bent Over MB Chest Slam": "https://www.youtube.com/watch?v=pnKdPGpyz00",
  "Bird Dog Row": "https://www.youtube.com/watch?v=IrMVMZoQum4",
  "Box Jump to Land": "https://www.youtube.com/shorts/Qx-ZdSySbhg",
  "Chin Up Iso Hold Knee Raise": "https://www.youtube.com/shorts/b52OZDygTDI",
  "DB Alt Floor Press": "https://www.youtube.com/shorts/nqZcpsqTvrw",
  "DB Lateral Weight Shift": "https://www.youtube.com/watch?v=eMsMvK517lE",
  "DB Pause Flat Press": "https://www.youtube.com/shorts/_CaZNkH9Vh0",
  "DB RFE Split Squat": "https://www.youtube.com/watch?v=0wkMqt0d3so",
  "DB SA Floor Press": "https://www.youtube.com/shorts/KVpKbRVNrZ4",
  "DB SL Glute Bridge": "https://www.youtube.com/shorts/bRZeB6UG6Js",
  "DB Side Bend": "https://www.youtube.com/shorts/2h2-WikKlp0",
  "DB Split Squat": "https://www.youtube.com/shorts/qW2ps30p9m4",
  "DB Squat Jump": "https://www.youtube.com/shorts/bhi4yXKuVek",
  "DB Tripod Row": "https://www.youtube.com/shorts/l39wliOe0z0",
  "DB Wrist Extension and Flexion": "https://www.youtube.com/shorts/I0nZ6Ij4ZLE",
  "DNS Star": "https://www.youtube.com/shorts/JZi_sc1kpcg",
  "FFE Goblet Split Squat": "https://www.youtube.com/shorts/wCishRH6bGs",
  "Hamstring Iso w/ OH DB Flexion": "https://www.youtube.com/shorts/azIvHDfhASU",
  "Hand Supported Step Down": "https://www.youtube.com/shorts/bg6DxG1Mqck",
  "Hanging MB Knee Raise": "https://www.youtube.com/shorts/1SKkIiDP9kQ",
  "Hanging Scapular Retraction": "https://www.youtube.com/shorts/C83rJJ0he_I",
  "Horizontal Bar Row w/ Hand Release": "https://www.youtube.com/shorts/vZy_Eu_Z0WA",
  "Incline DB Row": "https://www.youtube.com/shorts/b_QO3PedVR8",
  "KB Hip Airplane": "https://www.youtube.com/shorts/lclskoCDO4A",
  "Knee on Bench Row": "https://www.youtube.com/shorts/LbcX0Bj-XJU",
  "Lateral Bear Crawl Walk": "https://www.youtube.com/watch?v=IEbflSNpO3E",
  "Lateral Lunge Drop from Box": "https://www.youtube.com/shorts/A-01aEKyDb8",
  "MB Slam": "https://www.youtube.com/shorts/reIpHeafMuc",
  "MB Slam to Vert Jump": "https://www.youtube.com/shorts/nRdUVKc4Yv0",
  "Pause Goblet Squat": "https://www.youtube.com/shorts/n8ClCGBt2zA",
  "Pause Incline DB Press": "https://www.youtube.com/shorts/hvAN-7kPxH0",
  "Pause KB RDL": "https://www.youtube.com/shorts/af-Y3QGn8LU",
  "Plate Lateral Box Step Down": "https://www.youtube.com/shorts/Tm_WR_GMMx4",
  "Pull Ups": "https://www.youtube.com/shorts/PbfFblcxWSo",
  "Rack Supported SL RDL": "https://www.youtube.com/shorts/Ex_pPwkzS1k",
  "SL Bent Knee Calf Raise": "https://www.youtube.com/shorts/cNfTqm87-54",
  "Safety Bar Squat Heels Elevated": "https://www.youtube.com/watch?v=QCL7wxO__Mg",
  "Seated Vert Jump to Vert Jump": "https://www.youtube.com/watch?v=73KDmeLwcjI",
  "Seated Vertical Jump": "https://www.youtube.com/shorts/Y0eyBMCPvDg",
  "T-Spine Rotation": "https://www.youtube.com/shorts/U84XNDNDWco",
  "Tricep Pulldown": "https://www.youtube.com/shorts/xguGXQAvbKk",
  "Weighted Pause Push Up": "https://www.youtube.com/shorts/zKBVnHdmbLA",
  "Weighted Pull Ups": "https://www.youtube.com/shorts/c11yAY7r3io",
  "Weighted Side Plank": "https://www.youtube.com/shorts/zbXNrI0hzPU",
  "Zottman Curls": "https://www.youtube.com/shorts/4atCzx_QIHY",
};

export const EXERCISE_NOTES = {
  'DB Wrist Extension and Flexion': 'Slow as able',
  'Monkey Bar Chin-Up': 'Complete a chin-up on the monkey bars',
};
